
 #----------------------------------building step-----------------------------------
#create the base layer
FROM node:latest as build

WORKDIR /app
COPY . /app/
RUN npm install
#build the app
RUN npm run build --prod
RUN ls

#---------------------------------deployment step-------------------------------------
# set up nginx as web service
FROM nginx:alpine
# replacing the default content of ngnix by the app generated by angular
COPY --from=build /app/dist/angular-front usr/share/nginx/html
#specify expose port
EXPOSE 80
